### ISSUE TITLE
Plugin Installation breaks v1.16.3 

### ISSUE THREAD

**Issue by ArchWinDoors** [msigley/osticket-msgraph-mailfetcher#1]
AH01071: Got error 'PHP message: PHP Fatal error:  Declaration of MSGraphPluginConfig::pre_save($config, &$errors) must be compatible with PluginConfig::pre_save(&$config, &$errors) in /var/www/support/include/plugins/msgraph/config.php on line 65'
referer: https://yourdomainname/scp/plugins.php?a=add

**Comment by msigley** [comment]
It looks like this issue affects all v1.16.x and is caused by this commit:
https://github.com/osTicket/osTicket/commit/ec9c09d027acd2c9e9eb0f60b8464abe8c6c7cf9

**Comment by msigley** [comment]
Fixed in 29a4ba4407b986f4eb9e1a6320cc4ce285b2ad8e
